language: python
python:
  - 3.5
install:
  - pip install -q pytest pytest-pep8 errbot coverage --use-wheel
  - pip install -r requirements.txt --use-wheel
script:
  - coverage run --source ddog -m py.test
after_success:
  - coveralls
notifications:
  email: false
